# Generated by Django 4.1.7 on 2023-03-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_posts_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={"verbose_name_plural": "Our Posts"},
        ),
    ]
