# Generated by Django 4.1.7 on 2023-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_posts_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.SmallIntegerField()),
                ("image", models.ImageField(upload_to="customers/")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("join_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Our Customers",
            },
        ),
    ]
