# Generated by Django 4.1.7 on 2023-03-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="age",
            field=models.SmallIntegerField(default=18),
        ),
    ]
