# Generated by Django 4.1.7 on 2023-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_customers_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="age",
            field=models.SmallIntegerField(default=18, verbose_name="customer age"),
        ),
        migrations.AlterField(
            model_name="customers",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="customer email"),
        ),
        migrations.AlterField(
            model_name="customers",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female")],
                default="male",
                max_length=200,
                verbose_name="customer gender",
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="image",
            field=models.ImageField(
                upload_to="customers/", verbose_name="customer profile"
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="join_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="customer join at"
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="name",
            field=models.CharField(max_length=200, verbose_name="customer name"),
        ),
    ]
