# Generated by Django 4.1.7 on 2023-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_customers_age_alter_customers_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="post created at"),
        ),
    ]
