# Generated by Django 4.1.7 on 2023-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_posts_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="post created at"),
        ),
    ]
