# Generated by Django 4.1.7 on 2023-03-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentsReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField()),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.comments"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comments Reply",
            },
        ),
    ]
