# Generated by Django 4.1.7 on 2023-03-13 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_commentsreply"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_react",
                    models.CharField(
                        choices=[
                            ("LIKE", "LIKE"),
                            ("LOVE", "LOVE"),
                            ("SAD", "SAD"),
                            ("CARE", "CARE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.posts"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post React",
            },
        ),
    ]
