# Generated by Django 4.1.7 on 2023-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_alter_postreact_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreact",
            name="post_react",
            field=models.CharField(
                choices=[
                    ("LIKE", "LIKE"),
                    ("LOVE", "LOVE"),
                    ("SAD", "SAD"),
                    ("CARE", "CARE"),
                ],
                default="LIKE",
                max_length=10,
            ),
        ),
    ]
